### PR TITLE
Implement upcoming matches

### PR DESCRIPTION
**Pull request by mammuth**
This PR adds a new function to the API for getting upcoming matches.
It even has a feature that the node package is lacking: Filtering for teams

I also added tests for the new features; might be a good idea to add it to the other functions.

### CODE REVIEW

**Review by Olament — APPROVED** [review]
Great work! Merged. 
Yes it is a good idea to add tests for other methods. I will do that once i have time to finish the match-related functions.

**Comment by mammuth** [comment]
Hey @Olament, could you also release a new version? This would make it easier / nicer to use the new features in the library 😊

**Comment by Olament** [comment]
@mammuth Done. check https://github.com/Olament/HLTV-Go/releases/tag/v0.2.0

**Comment by mammuth** [comment]
Perfect, thanks

**Pull request merged**
